
ecip:
  devMode: true

server:
  port: 8899
  use-forward-headers: true
  servlet:
    context-path: /quartz
  tomcat:
    uri-encoding: UTF-8
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port

spring:
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreCMT
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

    #数据库方式
    job-store-type: jdbc
  cache:
    ehcache:
      config: classpath:ehcache/ehcache.xml
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
  datasource:
    main:
      type: com.alibaba.druid.pool.DruidDataSource

      #sqlserver
#      url: jdbc:mysql://10.173.205.41:1433;databaseName=ecip;SelectMethod=cursor
      url: jdbc:mysql://192.168.65.130:3306/springboot-quartz
      username: root
      password: 123456
      validationQuery: select GETDATE()

      #mysql
      #      url: jdbc:mysql://10.173.205.92:3306/ecip?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      #      username: root
      #      password: hgrica1@
      #      validationQuery: SELECT 'x'

      #oracle
      #      url: jdbc:oracle:thin:@10.173.205.92:1521/pdborcl
      #      username: ecip
      #      password: hgrica1024
      #      validationQuery: select 1 from dual

      #配置初始化大小、最小、最大
      initialSize: 10
      minIdle: 20
      maxActive: 100
      #配置获取连接等待超时的时间
      maxWait: 20000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 100

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

  flyway:
    enabled: false
    baseline-on-migrate: true

#mybatis-plus:
#  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
##  mapper-locations: classpath:/com/hgsoft/*/*/*/dao/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
##  typeAliasesPackage: com.hgsoft.*.*.*.entity
#  global-config:
#    db-config:
#      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: input
#      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: NOT_NULL
#      #驼峰下划线转换
#      #        db-column-underline: true
#      #mp2.3+ 全局表前缀 mp_
#      #table-prefix: mp_
#      #刷新mapper 调试神器
#      #refresh-mapper: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      # Sequence序列接口实现类配置
#      #    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#      #逻辑删除配置（下面3个配置）
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#      #自定义填充策略接口实现
#    #    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
#  configuration:
#    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'

#id生成配置
#当有多个web服务器时，workerId应该设置为不同
workerId: 0
#数据中心id
dataCenterId: 0
superUser: admin

loginRetryCount: 5

jwt:
  #  header: Authorization
  token:
    secret: mySecret
    #    7天
    #    expiration: 604800

    #    一天
    expiration: 86400
